import {
  faSignOutAlt,
  faHome,
  faFolderOpen,
  faHeartbeat,
  faBriefcaseMedical,
  faEnvelope,
  faAngleRight,
  faHeadset,
  faBell,
  faCaretDown,
  faHeadphones,
  faEllipsisH,
  faAngleLeft,
  faMapMarkerAlt,
  faCalendarAlt,
  faClock,
  faCheck,
  faTimes,
} from '@fortawesome/free-solid-svg-icons';

export default [
  faSignOutAlt,
  faHome,
  faFolderOpen,
  faHeartbeat,
  faBriefcaseMedical,
  faEnvelope,
  faAngleRight,
  faHeadset,
  faBell,
  faCaretDown,
  faHeadphones,
  faEllipsisH,
  faAngleLeft,
  faMapMarkerAlt,
  faCalendarAlt,
  faClock,
  faCheck,
  faTimes,
];
